# Generated by Django 6.0.2 on 2026-03-11 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_api', '0002_chatmessage_chatsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='paper',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='research_api.chatsession'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
