# Generated by Django 6.0.2 on 2026-03-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_api', '0003_remove_chatmessage_paper_chatmessage_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
