# Generated by Django 6.0.2 on 2026-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_api', '0004_chatsession_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='concept_map_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
