# Generated by Django 6.0.2 on 2026-04-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_api', '0005_researchpaper_concept_map_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
